version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/:/app/"
    command: "run --enable-api --debug"

  action_server:
#    image: rasa/rasa-sdk:latest
    build: 
      context: .
      dockerfile: Dockerfile
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"
    
  rasa_ui:       
    image: paschmann/rasa-ui:latest
    container_name: rasa_ui
    networks: ['rasa-network']
    ports:
      - "8080:8080"
    depends_on:
      - "rasa"
    environment:
      rasa_endpoint: "http://rasa:5005"
