version: '3.0'

services:
  rasa:
    build: 
      context: .
      dockerfile: Dockerfile
 #   image: rasa/rasa:latest-full
#    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - rasa_models:/app/models
    - "./rasa-app-data/:/app/"
    command:  
      - train
      - --augmentation
      - 0
#       - &&
#       - rasa
#       - run  
#       - -m  
#       - models   
#       - --enable-api  
#       - --cors   
#       - "*"  
#       - --debug   
#  command: >
#    &&
#    run
#    --debug 
#    --enable-api 
#    -p 5005
#       - /bin/bash
#       - -c
#       - |
#         if not [ -d "/app/models" ]; then
#           echo "Installing and training model files in /app/models..."
#           rasa train --augmentation 0
#           echo "Model Training successful! (/app/models)"
#         fi
#         rasa run --enable-api --debug
  action_server:
#    image: rasa/rasa-sdk:latest
    build: 
      context: .
      dockerfile: Dockerfile
#    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
#    networks: ['rasa-network']
    ports:
    - "8000:8000"
    
  rasa_ui:       
    image: paschmann/rasa-ui:latest
    container_name: rasa_ui
 #   networks: ['rasa-network']
    ports:
      - "8080:8080"
    depends_on:
      - "rasa"
    environment:
      rasa_endpoint: "http://rasa:5005"
volumes:
  rasa_models:
